/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WR5B6P9MRwt
 */

import Image from 'next/image'

export function Skills() {
  return (
    <section id="skills" className="w-full h-[100vh] grid py-12 lg:py-16">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <div className="space-y-1">
            <AwardIcon className="mx-auto w-12 h-12 rounded-full bg-gray-100 p-3 grid place-items-center dark:bg-gray-800" />
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              My Favorite Frameworks
            </h2>
          </div>
        </div>
        <div className="mx-auto grid max-w-sm grid-cols-3 items-center justify-center gap-4 lg:max-w-none lg:grid-cols-3">
          <div className="flex flex-col items-center justify-center space-y-1">
            <Image
              alt="Qwik.js"
              className="rounded-full border aspect-square object-cover"
              height="100"
              src="/placeholder.svg"
              width="100"
            />
            <MedalIcon className="w-8 h-8" />
            <span className="font-semibold">Qwik.js</span>
          </div>
          <div className="flex flex-col items-center justify-center space-y-1">
            <Image
              alt="Next.js"
              className="rounded-full border aspect-square object-cover"
              height="100"
              src="/placeholder.svg"
              width="100"
            />
            <MedalIcon className="w-8 h-8" />
            <span className="font-semibold">Next.js</span>
          </div>
          <div className="flex flex-col items-center justify-center space-y-1">
            <Image
              alt="React"
              className="rounded-full border aspect-square object-cover"
              height="100"
              src="/placeholder.svg"
              width="100"
            />
            <MedalIcon className="w-8 h-8" />
            <span className="font-semibold">React</span>
          </div>
        </div>
        <div className="mx-auto max-w-2xl">
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Qwik.js is my favorite framework because of its speed and
            simplicity. Next.js is a close second, and I love its SSR and built
            in features. React, as the foundation of the other two, is simply
            indispensable.
          </p>
        </div>
      </div>
    </section>
  )
}

function AwardIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}

function MedalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </svg>
  )
}
